name: CashOverflowUz
on:
  push:
    branches:
    - Main
  pull_request:
    branches:
    - Main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checking out
      uses: actions/checkout@v2
    - name: Instaling .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.200
        include-prerelease: false
    - name: Restoring packages...
      run: dotnet restore
    - name: Building project
      run: dotnet build --no-restore
    - name: Testing project
      run: dotnet test --no-build --verbosity normal
